export default {
    "adagio": "slow tempo",
    "amoroso": "loving",
    "allegro": "fast and lively tempo",
    "andante": "walking tempo",
    "animato": "animated",
    "assai": "very much",
    "bravura": "boldy",
    "capo": "head",
    "comodo": "comfortable",
    "con": "with",
    "con brio": "with vigor",
    "decelerando": "slowing down",
    "dolce": "sweetly",
    "eroico": "heroically",
    "facile": "easily",
    "fuocoso": "fiery",
    "gentile": "gently",
    "grandioso": "grandly",
    "grave": "slow and serious",
    "grazioso": "gracefully",
    "gustoso": "with happy emphasis and forcefulness",
    "irato": "angrily",
    "piano": "soft",
    "largo": "broadly/slowly",
    "legato": "connected",
    "leggiero": "lightly",
    "lento": "slowly",
    "ma non troppo": "not too much",
    "maestoso": "majestically",
    "marcato": "marked, accented",
    "mezzo-piano": "medium soft",
    "mezzo-forte": "medium loud",
    "moderato": "moderate",
    "modulation": "change key",
    "molto": "very",
    "forte": "loud",
    "fortissimo": "very loud",
    "cadenza": "extended solo",
    "vivace": "lively"
}