export default {
  adagio: "slow tempo (66-76bpm)",
  amoroso: "loving",
  allegro: "fast and lively tempo",
  andante: "walking tempo",
  animato: "animated",
  assai: "very much",
  bravura: "boldy",
  cadenza: "extended solo",
  capo: "head",
  comodo: "comfortable",
  con: "with",
  "con brio": "with vigor",
  crescendo: "gradual increase in volume",
  decelerando: "slowing down",
  dolce: "sweetly",
  eroico: "heroically",
  facile: "easily",
  fermata: "pause on note",
  forte: "loud",
  fortissimo: "very loud",
  fuocoso: "fiery",
  gentile: "gently",
  grandioso: "grandly",
  grave: "slow and serious",
  grazioso: "gracefully",
  gustoso: "with happy emphasis and forcefulness",
  irato: "angrily",
  largo: "broadly/slowly",
  legato: "connected",
  leggiero: "lightly",
  lento: "slowly (45-60bpm)",
  "ma non troppo": "not too much",
  maestoso: "majestically",
  marcato: "marked, accented",
  meno: "less",
  "mezza voce": "half voice",
  "mezzo-piano": "medium soft",
  "mezzo-forte": "medium loud",
  moderato: "moderate",
  modesto: "modest",
  modulation: "change key",
  molto: "very",
  morendo: "dying",
  patetico: "passionately, with great emotion",
  pesante: "heavy, ponderous",
  piano: "soft",
  pianissimo: "very soft",
  poco: "a little",
  presto: "very fast tempo",
  prestissimo: "extremely quickly, as fast as possible",
  rubato: "flexible in tempo",
  sempre: "always",
  senza: "without",
  sostenuto: "sustained, lengthened",
  sforzando: "forced",
  stacatto: "detached, note of shortened duration",
  subito: "suddenly",
  ternary: "three part musical form",
  tenuto: "play note slightly longer",
  tranquillo: "calmly, peacefully",
  tremelo: "rapid repetition/alternation of notes",
  "una corda": "one string, soft pedal",
  vivace: "lively"
};
